### ISSUE TITLE
Pass in values from prompt?

### ISSUE THREAD

**Issue by valgaze** [cisco-ce/jsxapi#49]
Any plans to pass in the values (not just optionID) from prompt?

Currently prompt only passes back FeedbackID, OptionId but not the choice value

From page 230: https://www.cisco.com/c/dam/en/us/td/docs/telepresence/endpoint/ce93/collaboration-endpoint-software-api-reference-guide-ce93.pdf

![image](https://user-images.githubusercontent.com/1396559/70078413-7d15ca80-15b7-11ea-83bb-5da43b55cc0a.png)

**Comment by myme** [comment]
This library is for interfacing with the `XAPI`, not a support space for the `XAPI` specification and behavior. Issues not relevant to the `JavaScript/TypeScript` code in this repository will be closed.

That said, you're more than welcome to e.g. join one of our support spaces on Webex Teams, or contact Cisco through other means: https://github.com/cisco-ce/jsxapi#questions-and-support

**Comment by valgaze** [comment]
@myme  Understood-- I was curious specifically about roadmap regarding payloads returned the JSXAPI *"events"*-- ie the event payload from ```Prompt Response``` returns OptionId and not its corresponding "value" from the prompt choices. 

Just a convenience thing -- ex below's event payload:

```js
const xapi = require("xapi");

const feedbackId = "prompt123";
const config = {
  Title: "Prompt Title",
  Text: "Prompt Text",
  FeedbackId: feedbackId,
  "Option.1": "choice a",
  "Option.2": "choice b",
  "Option.3": "choice c"
}

xapi.command("UserInterface Message Prompt Display", config);

xapi.event.on("UserInterface Message Prompt Response", event => {
  console.log(event); // { id: '1', FeedbackId: 'prompt123', OptionId: '2' }
});

```

But it makes sense to me that this library shouldn't drift/deviate in any way from specified XAPI payloads-- the XAPI spec drives JSXAPI and not vice versa.

**Comment by myme** [comment]
Yes, now you're touching on something else, which is really interesting. The goal of `jsxapi` is primarily to be a "no surprises" low-level binding to the `XAPI`. However, using the `jsxapi` it's fully possible to create overlays or higher-lever APIs which iron out nits and inconveniences like this one. For instance taking your use-case as an example, it's not possible with the current `Prompt` API to create a fully stateless service, because you have to keep track of which are the options that were passed to the user. If these are dynamically generated, then the control device or service must remember this somehow.

In a `nodejs`/`macros` context, you could imagine creating a wrapper function which encapsulates this though:

```javascript
const xapi = require('xapi');

let nextFeedbackId = 1;

async function prompt(Title, Text, options) {
  const opts = {};
  const FeedbackId = nextFeedbackId++;

  for (let i = 0; i < Math.min(5, options.length); i++) {
    opts[`Option.${i + 1}`] = options[i];
  }

  console.log('FeedbackId:', FeedbackId);
  await xapi.command("UserInterface Message Prompt Display", Object.assign({
    Title,
    Text,
    FeedbackId,
  }, opts));

  const reply = await new Promise((resolve) => {
    const off = xapi.event.on('UserInterface Message Prompt Response', (event) => {
      if (parseInt(event.FeedbackId, 10) === FeedbackId) {
        off();
        resolve(event);
      }
    });
  });

  const optIdx = parseInt(reply.OptionId, 10);
  return options[optIdx - 1];
}

async function runPrompt() {
  const reply = await prompt('This is title', 'This is text', ['Foo', 'Bar', 'Baz']);
  console.log('Prompt reply:', reply);
}

runPrompt();
```

Stuff like this is beyond this library though, but that shouldn't stop anyone from creating a project or module which starts to built utilities like this one.

**Comment by valgaze** [comment]
@myme Funny you say that, I’ve got something in the works you might interesting. I’ll reach out when I release!

Thanks!
